=== ASSIKPAIzandine-dev/projet_training/projet_L1/dossier_l1/bibliographie.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bibliographie (livres,articles)>
<!ELEMENT livres (livre+)>
<!ELEMENT livre (titre,auteur,tomes,infosedition,avis?)>
<!ELEMENT titre (#PCDATA)>
<!ATTLIST titre soustitre CDATA #REQUIRED>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT tomes (tome+)>
<!ELEMENT tome EMPTY>
<!ATTLIST tome nbpage CDATA #REQUIRED soustitre CDATA #IMPLIED>
<!ELEMENT infosedition (editeur,lieuedition,lieuimpression,ISBN)>
<!ELEMENT editeur (#PCDATA)> <!ELEMENT lieuedition (#PCDATA)>
<!ELEMENT lieuimpression (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)> 
<!ELEMENT avis (#PCDATA)>
<!ELEMENT articles (article+)>
<!ELEMENT article (titre,auteur,infospublication,avis)>
<!ELEMENT infospublication (pages,anneepublication,numerojournal)>
<!ATTLIST infospublication nomjournal CDATA "sokode infos">
<!ELEMENT pages (#PCDATA)>
<!ELEMENT anneepublication (#PCDATA)>
<!ELEMENT numerojournal (#PCDATA)>

=== ASSIKPAIzandine-dev/projet_training/projet_L1/dossier_l1/bibliographie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliographie SYSTEM "bibliographie.dtd">
<bibliographie>
   <livres>
     <livre>
       <titre soustitre="les vases de la membranes"> le titre d'une activite </titre>
       <auteur> un auteur du temps passe</auteur>
       <tomes>
         <tome nbpage="pages 20" soustitre="colonisation"/>
       </tomes>
       <infosedition>
         <editeur>l'editeur peut étre connu</editeur>
         <lieuedition>lieu d'edition de pilon</lieuedition>
         <lieuimpression>lieu etait a lome</lieuimpression>
         <ISBN>numero 2542-784</ISBN>
       </infosedition> 
       <avis>mon avis compte sur ce livre</avis>     
      </livre>
    </livres>
    <articles>   
      <article>
        <titre soustitre="les  soustitres de decentralistion">introduction a xml</titre>
        <auteur>l'auteur de eza botto</auteur>
        <infospublication nomjournal ="sokode infos">
          <pages>les pages au total 120</pages>
          <anneepublication>ils ont publié en 1998</anneepublication>
          <numerojournal>un numero 25-58000</numerojournal>
        </infospublication> 
        <avis>mon avis est partagé avec succè</avis>
      </article>
    </articles>   
</bibliographie>
