=== ASSIKPAIzandine-dev/projet_training/projet_L1/dossier_l1/galerie.dtd
<?xml version="1.0" encoding="UTF-8"?>
 <!ELEMENT galeries (galerie+)>
 <!ELEMENT galerie (gerant,contenu)>
 <!ATTLIST galerie adresse CDATA  #REQUIRED>
 <!ELEMENT gerant (#PCDATA)>
 <!ELEMENT contenu (type,auteur,titre?,prix?)>
 <!ELEMENT type (#PCDATA)>
 <!ELEMENT auteur (#PCDATA)>
 <!ELEMENT titre (#PCDATA)>
 <!ELEMENT prix (#PCDATA)>

=== ASSIKPAIzandine-dev/projet_training/projet_L1/dossier_l1/Galerie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE galeries SYSTEM  "galerie.dtd">
 <galeries>
 
    <galerie adresse="kpangalame">
            
       <gerant>il geree une fois par jours </gerant>
       <contenu>
          <type> les elements sont de types verbales</type>
          <auteur> les auteurs de jean de la fontaine</auteur>
          <titre> un titre convenables</titre>
          <prix> le prix sera fixe des lors</prix>
        </contenu>
            
     </galerie>      
      
      
      
      
   
  </galeries>
